# Generated by Django 6.0.4 on 2026-04-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='theory_image',
            field=models.ImageField(blank=True, null=True, upload_to='theory_images/', verbose_name='Теория суреті'),
        ),
    ]
