# Generated by Django 6.0.4 on 2026-04-12 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quiz_theory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='core.quiz', verbose_name='Көшірілген тесттен'),
        ),
    ]
