# Generated by Django 6.0.4 on 2026-04-16 17:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiz_copied_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_marketplace',
            field=models.BooleanField(default=False, verbose_name='Маркетплейсте қол жетімді'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='theory_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='theory_image'),
        ),
    ]
